---@class SignatureContent
---@field contents table | nil The contents of the signature
---@field active_hl table | nil The active highlight of the signature
---@field label_line integer The line of the signature's label, used for highlighting
---@field add_content function Adds the contents of the signature to the signature content object

---@class Signature
---@field err table | nil The error message
---@field mode string The current mode
---@field ctx table The context
---@field config table The configuration
---@field signatures table The signatures
---@field mappings table<number, table<string, string>> The mapping list, indexed first by buffer number, then by mapping name, giving the lhs value of the mapping
---@field original_buf_mappings table<number, table<string, table>> The mapping list, indexed first by buffer number, then by lhs, giving the maparg() dictionary value of the mapping
---@field signature_content SignatureContent The signature content
